### PR TITLE
Add support for pug (aka new jade) see

### PR DESCRIPTION
**Pull request by hthetiot**
add pub (aka new 'jade') support in doc with tests, keep 'jade' tests and support in doc.
See issue #222

### CODE REVIEW

**Comment by hthetiot** [comment]
@niftylettuce That was quick THX!

**Comment by hthetiot** [comment]
@niftylettuce the travis failed weirdly.
- https://travis-ci.org/crocodilejs/node-email-templates/jobs/226951239

But test pass for me and i saw travis passed early, dont know where.

Let see of the merge goes:
- https://travis-ci.org/crocodilejs/node-email-templates/builds/226951502

**Comment by niftylettuce** [comment]
@hthetiot just published v2.5.6 version to NPM, `npm install --save email-templates@2.5.6`

Join us in Slack at http://slack.crocodilejs.com 👍  Thank you for PR.

**Comment by hthetiot** [comment]
Travis merge succeeded.
- https://travis-ci.org/crocodilejs/node-email-templates/builds/226951502

**Pull request merged**
